"""Emit docs/generated/build_status.md: per planned table, built / partial / blocked.

Inspects each run_tag's cache (predictions + results) and applies the known-blocker
registry (pending InternVL rerun, H100 G2 inference, un-run DPI sweep, resolution
CUDA faults) so no blocked table is ever shipped from partial data as if complete.
"""

from __future__ import annotations

from pathlib import Path

from config import ROOT, ExperimentConfig
from experiments.engine.paths import experiment_paths

G1, G2, G3 = "G1_oracle_ladder", "G2_retrieval", "G3_hallucination"

# One row per planned table: (table, task, source run_tag, blocked/partial reason or "").
# An empty reason means "build when the source run is judged".
PLANNED = [
    ("headline", G1, "g1-representation-full", ""),
    ("composition", G1, "g1-representation-full", ""),
    ("parser (paddleocrvl)", G1, "g1-representation-full", "paddleocrvl TL/TLV; mineru is a second parser (g1-parser-full-mineru), a merged comparison needs a cross-run_tag build"),
    ("parser (mineru)", G1, "g1-parser-full-mineru", "mineru TL/TLV; build once judged"),
    ("scale (model-size)", G1, "g1-reasoner-full", ""),
    ("scale (quantization)", G1, "g1-quantization-full", ""),
    ("resolution", G1, "g1-resolution-full", "the 488 CUDA-fault cells were rerun and fixed (err=0); remaining gap is the OOM tail + unjudged new cells"),
    ("routing", G1, "g1-representation-full", "needs g3 classifier price for predicted_routing"),
    # internvl_family is special-cased in render(): built once the reasoner run has
    # judged internvl cells, else blocked on the einops --failed-only rerun.
    ("internvl_family", G1, "g1-reasoner-full", "@internvl"),
    ("retrieval_accuracy (doc_type)", G2, "g2-retrieval-full", "side artifact (benchmark complete), no judge needed"),
    ("retrieval_accuracy_overall", G2, "g2-retrieval-full", "side artifact (benchmark complete), no judge needed"),
    ("retrieval_dpi", G2, "g2-dpi", "BLOCKED: DPI sweep not run (separate retrieval-only pass)"),
    ("matched_cross", G2, "g2-retrieval-full", "BLOCKED: reasoner inference 4137/15246; resuming on Kaya job 1061344, else finishes on H100"),
    ("kdepth", G2, "g2-retrieval-full", "BLOCKED: reasoner inference 4137/15246; resuming on Kaya job 1061344, else finishes on H100"),
    ("hallucination", G3, "g3-hallucination-full", "243 cells CUDA-faulted (node fault, not judged); builds from the ok cells"),
]


def _counts(run_tag: str, task: str) -> tuple[bool, bool, int, int]:
    """(predictions_exist, results_exist, ok_cells, judged_ok_cells)."""

    paths = experiment_paths(ExperimentConfig(run_tag=run_tag), task)
    pred_ok = res_ok = 0
    has_pred = paths.predictions.exists()
    has_res = paths.results.exists()
    if has_pred:
        pred_ok = sum(1 for ln in paths.predictions.read_text().splitlines()
                      if ln.strip() and '"status": "ok"' in ln)
    if has_res:
        res_ok = sum(1 for ln in paths.results.read_text().splitlines()
                     if ln.strip() and '"status": "ok"' in ln)
    return has_pred, has_res, pred_ok, res_ok


def _counts_sub(run_tag: str, task: str, sub: str) -> int:
    """Judged-ok rows whose line contains `sub` (e.g. a model_spec substring)."""

    paths = experiment_paths(ExperimentConfig(run_tag=run_tag), task)
    if not paths.results.exists():
        return 0
    return sum(1 for ln in paths.results.read_text().splitlines()
               if ln.strip() and '"status": "ok"' in ln and sub in ln)


def _status(reason: str, has_pred: bool, has_res: bool, res_ok: int) -> str:
    if reason.startswith("BLOCKED"):
        return "blocked"
    if reason.startswith("PARTIAL"):
        return "partial" if has_res and res_ok else "partial (pending judge)"
    if "side artifact" in reason:
        return "built" if has_pred else "blocked (no side artifact)"
    if has_res and res_ok:
        return "built"
    if has_pred:
        return "pending judge"
    return "missing"


def render() -> str:
    lines = [
        "# Build-status manifest",
        "",
        "Generated by `ops/scripts/build_status.py`. One row per planned table: whether it "
        "builds now, is partial, is blocked on a pending generation pass, or is still waiting "
        "on the judge. No blocked table is built from partial data as if complete.",
        "",
        "| table | task | source run_tag | status | judged_ok | reason / note |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for table, task, run_tag, reason in PLANNED:
        has_pred, has_res, pred_ok, res_ok = _counts(run_tag, task)
        if reason == "@internvl":
            # Built once the reasoner run has judged internvl cells; else blocked on the rerun.
            res_ok = _counts_sub(run_tag, task, "internvl")
            if res_ok:
                status, note = "built", "InternVL arm judged (family replication available)"
            else:
                status, note = "blocked", "BLOCKED: InternVL arm not yet judged (einops --failed-only rerun / pull pending)"
            lines.append(f"| {table} | {task} | {run_tag} | {status} | {res_ok} | {note} |")
            continue
        status = _status(reason, has_pred, has_res, res_ok)
        note = reason or ("ready" if status == "built" else "judge this run to build")
        lines.append(f"| {table} | {task} | {run_tag} | {status} | {res_ok} | {note} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    out = ROOT / "docs" / "generated" / "build_status.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render())
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
