"""Append a concise Python module map to docs/REPO_STRUCTURE.md.

Walks the repo (skipping virtualenvs, caches, data, results, and other gitignored
heavy dirs), reads each `.py` file's top-of-file `\"\"\"...\"\"\"` module docstring via
`ast`, and writes a filtered per-directory listing into the auto-generated section
of docs/REPO_STRUCTURE.md. Package markers and tests are omitted, and each retained
module is reduced to the first useful purpose sentence so the section stays usable
as a repo-rework map rather than a verbatim documentation dump.

Usage: python -m ops.scripts.dump_docstrings
"""

from __future__ import annotations

import ast
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DOC = REPO / "docs" / "REPO_STRUCTURE.md"
MARKER = "## Per-file module docstrings (auto-generated)"

# Optional per-file summary overrides, keyed by repo-relative path. Normally
# empty: the source of truth is each module's own docstring (fixed in the .py
# and regenerated here), never a hand-written summary in this map.
SUMMARY_OVERRIDES: dict[Path, str] = {}

# Directory names pruned anywhere in the tree (heavy / vendored / generated).
SKIP_DIRS = {
    "envs", ".cache", ".data", "results", "logs", "__pycache__", ".git",
    ".pytest_cache", ".ruff_cache", ".mypy_cache", ".agents", ".codex",
    ".claude", ".vscode", "inspect", "temp",
}


def iter_py_files():
    for path in sorted(REPO.rglob("*.py")):
        rel = path.relative_to(REPO)
        if any(part in SKIP_DIRS for part in rel.parts):
            continue
        if rel.name == "__init__.py" or rel.parts[0] == "tests":
            continue
        yield rel, path


def module_docstring(path: Path) -> str | None:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except (SyntaxError, UnicodeDecodeError) as exc:
        return f"(could not parse: {exc})"
    return ast.get_docstring(tree, clean=True)


def group_key(rel: Path) -> str:
    return str(rel.parent) if str(rel.parent) != "." else "(root)"


def _purpose_text(doc: str) -> str:
    lines = doc.splitlines()
    for i, line in enumerate(lines):
        if line.strip() != "Purpose:":
            continue
        block: list[str] = []
        for raw in lines[i + 1:]:
            stripped = raw.strip()
            if re.fullmatch(r"[A-Z][A-Za-z0-9 /_-]*:", stripped):
                break
            if stripped:
                block.append(stripped)
        if block:
            return " ".join(block)
    return " ".join(line.strip() for line in lines if line.strip())


def short_summary(rel: Path, doc: str | None) -> str:
    if rel in SUMMARY_OVERRIDES:
        return SUMMARY_OVERRIDES[rel]
    if not doc:
        return "No module docstring."
    text = re.sub(r"\s+", " ", _purpose_text(doc)).strip()
    match = re.search(r"(?<=[.!?])\s+(?=[A-Z`])", text)
    if match:
        text = text[: match.start()]
    words = text.split()
    if len(words) > 32:
        text = " ".join(words[:32]).rstrip(".,;:") + "."
    return text


def build_section() -> str:
    groups: dict[str, list[tuple[Path, str | None]]] = {}
    for rel, path in iter_py_files():
        groups.setdefault(group_key(rel), []).append((rel, module_docstring(path)))

    lines = [
        MARKER,
        "",
        "Generated by `ops/scripts/dump_docstrings.py`, filtered for repo-rework use.",
        "Package markers and tests are omitted; each remaining entry is shortened",
        "to the first useful purpose sentence from the module docstring.",
        "",
    ]
    # (root) first, then the rest alphabetically.
    for key in sorted(groups, key=lambda k: (k != "(root)", k)):
        lines.append(f"### {key if key == '(root)' else key + '/'}")
        lines.append("")
        for rel, doc in groups[key]:
            lines.append(f"- **`{rel.as_posix()}`** — {short_summary(rel, doc)}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    base = DOC.read_text(encoding="utf-8")
    head = base.split(MARKER, 1)[0].rstrip() + "\n\n"
    DOC.write_text(head + build_section(), encoding="utf-8")
    n = sum(1 for _ in iter_py_files())
    print(f"Wrote {n} module docstrings into {DOC.relative_to(REPO)}")


if __name__ == "__main__":
    main()
